In [1]:
#importing useful libraries
import os
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import sklearn.preprocessing as skp 
import sklearn.model_selection as skm 

#import classification modules 

from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (accuracy_score, confusion_matrix, precision_score, recall_score,
roc_auc_score, roc_curve, auc, f1_score)

In [2]:
data = pd.read_csv("creditriskmodeling.csv")
print("Shape: ", data.shape,"\n")
print("Data Types: \n", data.dtypes)

Shape:  (424, 20)

Data Types:
 Default                                    object
Long Term Financing of Working Capital    float64
Working Capital Requirement               float64
Debt Cash Flow Coverage Ratio             float64
Liability to Equity                       float64
Net Debt to Equity Ratio                  float64
Debt to Capital Ratio                     float64
Long Term Debt to Asset                   float64
Long Term Debt to Tangible Asset          float64
Interest Coverage Ratio                   float64
Net Profit Margin                         float64
Gross Profit Margin                       float64
Return on Invested Capital                float64
Return on Equity                          float64
Fixed Asset to Debt Ratio                 float64
Short Term Debt to Sales Ratio            float64
Expense to Revenue Ratio                  float64
Fixed Asset Turnover                      float64
Collateral                                float64
Firm Size                                 float64
dtype: object

In [3]:
data.isnull().sum()

Default                                   34
Long Term Financing of Working Capital     0
Working Capital Requirement                0
Debt Cash Flow Coverage Ratio              0
Liability to Equity                        0
Net Debt to Equity Ratio                   0
Debt to Capital Ratio                      0
Long Term Debt to Asset                    0
Long Term Debt to Tangible Asset           0
Interest Coverage Ratio                    0
Net Profit Margin                          0
Gross Profit Margin                        0
Return on Invested Capital                 0
Return on Equity                           0
Fixed Asset to Debt Ratio                  0
Short Term Debt to Sales Ratio             0
Expense to Revenue Ratio                   0
Fixed Asset Turnover                       0
Collateral                                 0
Firm Size                                  0
dtype: int64

In [4]:
data.dropna(axis="rows", inplace=True)

In [5]:
data.isnull().sum()

Default                                   0
Long Term Financing of Working Capital    0
Working Capital Requirement               0
Debt Cash Flow Coverage Ratio             0
Liability to Equity                       0
Net Debt to Equity Ratio                  0
Debt to Capital Ratio                     0
Long Term Debt to Asset                   0
Long Term Debt to Tangible Asset          0
Interest Coverage Ratio                   0
Net Profit Margin                         0
Gross Profit Margin                       0
Return on Invested Capital                0
Return on Equity                          0
Fixed Asset to Debt Ratio                 0
Short Term Debt to Sales Ratio            0
Expense to Revenue Ratio                  0
Fixed Asset Turnover                      0
Collateral                                0
Firm Size                                 0
dtype: int64

In [6]:
y = data['Default'].copy()

In [7]:
x = data.drop('Default', axis="columns")

In [8]:
x

,Long Term Financing of Working Capital,Working Capital Requirement,Debt Cash Flow Coverage Ratio,Liability to Equity,Net Debt to Equity Ratio,Debt to Capital Ratio,Long Term Debt to Asset,Long Term Debt to Tangible Asset,Interest Coverage Ratio,Net Profit Margin,Gross Profit Margin,Return on Invested Capital,Return on Equity,Fixed Asset to Debt Ratio,Short Term Debt to Sales Ratio,Expense to Revenue Ratio,Fixed Asset Turnover,Collateral,Firm Size
0,18.535376,70.224272,2.221803,0.408836,0.345155,0.055726,3.340585,2.923488,1.068477,0.148902,0.753040,0.162915,0.599506,0.390593,2.558739,0.581809,0.308664,91.630740,597.117154
1,1.267586,68.542617,2.275505,0.152239,0.098785,0.212009,5.739963,1.060995,0.000368,0.033249,0.097175,0.600700,0.113056,2.448574,6.783702,0.300024,0.459017,26.895825,473.129644
2,26.770275,7.495582,0.842668,0.470291,1.186108,0.073379,2.640507,1.058287,0.227851,0.169472,0.678591,0.071966,0.108322,1.854344,5.192793,0.851202,0.526826,96.274755,449.378109
3,5.789437,17.879746,1.365122,0.045611,0.138333,0.010083,1.122648,0.274471,0.187073,0.142522,0.660062,0.119739,0.000152,3.136486,3.810741,2.598259,0.451532,17.562858,86.252204
4,11.863759,5.164020,0.061463,0.102421,0.046649,0.042453,5.229773,0.298343,0.121795,0.091286,0.317358,0.128427,0.075310,0.065888,0.109292,0.086590,0.579035,13.921293,90.903438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,2.967375,4.306767,1.195057,0.289187,0.197691,0.098885,1.580618,0.543355,0.249425,0.154862,0.082263,0.105435,0.019085,3.214324,0.558909,4.695348,0.013127,8.541653,45.557496
386,7.371987,8.274662,0.197746,0.347548,0.162002,0.084447,0.322341,0.531125,0.342126,0.166203,0.246791,0.410498,0.194504,0.302654,3.303260,0.764867,0.220998,0.636060,255.970266
387,1.277674,15.247391,0.087025,0.398516,0.143346,0.011864,1.766024,0.043377,0.815635,0.197306,0.079151,0.142845,0.266134,1.279593,0.690240,1.266123,0.006697,5.165972,183.810854
388,1.452352,36.271843,0.432011,0.127473,0.139109,0.003289,0.334501,0.302623,0.103090,0.028639,0.238410,0.319180,0.194369,2.457920,4.555444,0.318820,0.077891,12.137780,100.724959
389,3.361434,6.924909,0.292930,0.283283,0.126119,0.081141,1.542621,0.570353,0.538840,0.023312,0.046453,0.216475,0.451726,1.839406,4.997022,1.215211,0.004056,7.544936,582.419542

In [9]:
x.describe()

,Long Term Financing of Working Capital,Working Capital Requirement,Debt Cash Flow Coverage Ratio,Liability to Equity,Net Debt to Equity Ratio,Debt to Capital Ratio,Long Term Debt to Asset,Long Term Debt to Tangible Asset,Interest Coverage Ratio,Net Profit Margin,Gross Profit Margin,Return on Invested Capital,Return on Equity,Fixed Asset to Debt Ratio,Short Term Debt to Sales Ratio,Expense to Revenue Ratio,Fixed Asset Turnover,Collateral,Firm Size
count,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000,390.000000
mean,3.903772,36.761281,1.443091,0.121362,0.246491,0.105564,1.628648,0.700996,0.796386,0.065198,0.172114,0.245729,0.158487,1.700795,2.121750,0.726848,0.309412,16.168670,235.545890
std,3.323411,34.625261,1.188935,0.097363,0.198193,0.083685,1.326124,0.558180,0.626954,0.065646,0.137444,0.181783,0.122605,1.246879,1.672607,1.161816,0.253602,13.729438,169.408277
min,0.001129,0.035571,0.017170,0.001656,0.000631,0.000652,0.006490,0.008092,0.000368,0.000243,0.000391,0.001031,0.000069,0.052813,0.008077,0.002083,0.001696,0.037367,1.846764
25%,1.270108,10.188516,0.525813,0.049357,0.092078,0.042354,0.599707,0.252519,0.305548,0.024442,0.066677,0.106174,0.064601,0.724526,0.788297,0.141384,0.114291,5.241395,101.077142
50%,3.093474,26.108378,1.110742,0.104081,0.211370,0.083279,1.290844,0.572588,0.679601,0.045837,0.138961,0.203191,0.131965,1.470815,1.712664,0.288425,0.245010,13.350044,208.198668
75%,5.772506,56.488648,2.093631,0.166079,0.357713,0.147640,2.187441,1.029498,1.159327,0.082599,0.246741,0.342174,0.233750,2.480288,3.209083,0.655600,0.440162,23.251748,332.653041
max,26.770275,217.136290,5.864434,0.565904,1.214741,0.456129,6.609518,2.923488,3.321230,0.379519,0.753040,0.884435,0.628044,6.289680,7.852829,7.915658,1.602510,96.274755,924.729820

In [10]:
#standardize all numerical columns to the same range
x = skp.StandardScaler().fit(x).transform(x)
x

array([[ 4.40824111e+00,  9.67674304e-01,  6.55807464e-01, ...,
        -2.95130162e-03,  5.50342995e+00,  2.13706034e+00],
       [-7.94235698e-01,  9.19044604e-01,  7.01033525e-01, ...,
         5.90680965e-01,  7.82328738e-01,  1.40423443e+00],
       [ 6.88926908e+00, -8.46298064e-01, -5.05657628e-01, ...,
         8.58408267e-01,  5.84211681e+00,  1.26385142e+00],
       ...,
       [-7.91196191e-01, -6.22133226e-01, -1.14203709e+00, ...,
        -1.19519215e+00, -8.02423968e-01, -3.05778984e-01],
       [-7.38568848e-01, -1.41534455e-02, -8.51500444e-01, ...,
        -9.14102076e-01, -2.93971800e-01, -7.96856644e-01],
       [-1.63396515e-01, -8.62800660e-01, -9.68630525e-01, ...,
        -1.20561888e+00, -6.28926709e-01,  2.05019037e+00]])

In [11]:
X_DF = pd.DataFrame(x)

In [12]:
X_DF

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,4.408241,0.967674,0.655807,2.956399,0.498456,-0.596306,1.292591,3.986794,0.434546,1.276709,4.232057,-0.456152,3.601698,-1.052135,0.261598,-0.124999,-0.002951,5.503430,2.137060
1,-0.794236,0.919045,0.701034,0.317544,-0.746223,1.273615,3.104233,0.645781,-1.271290,-0.487308,-0.545932,1.955225,-0.371029,0.600491,2.790817,-0.367848,0.590681,0.782329,1.404234
2,6.889269,-0.846298,-0.505658,3.588402,4.747009,-0.385084,0.764000,0.640923,-0.907986,1.590458,3.689697,-0.957110,-0.409688,0.123305,1.838440,0.107171,0.858408,5.842117,1.263851
3,0.568117,-0.546011,-0.065663,-0.779023,-0.546422,-1.142426,-0.382053,-0.765117,-0.973111,1.179407,3.554716,-0.693972,-1.293089,1.152907,1.011092,1.612833,0.561127,0.101678,-0.882398
4,2.398202,-0.913722,-1.163565,-0.194780,-1.009618,-0.755115,2.719015,-0.722295,-1.077363,0.397911,1.058111,-0.646116,-0.679293,-1.312883,-1.204732,-0.551792,1.064540,-0.163901,-0.854907
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,-0.282120,-0.938511,-0.208887,1.725917,-0.246545,-0.079911,-0.036265,-0.282782,-0.873531,1.367618,-0.654563,-0.772759,-1.138469,1.215414,-0.935574,3.420161,-1.169805,-0.556236,-1.122923
386,1.044911,-0.823769,-1.048792,2.326106,-0.426849,-0.252662,-0.986322,-0.304721,-0.725482,1.540600,0.544023,0.907567,0.294143,-1.122753,0.707295,0.032765,-0.349077,-1.132789,0.120718
387,-0.791196,-0.622133,-1.142037,2.850259,-0.521096,-1.121116,0.103725,-1.179663,0.030742,2.014998,-0.677235,-0.566700,0.879122,-0.338238,-0.856955,0.464762,-1.195192,-0.802424,-0.305779
388,-0.738569,-0.014153,-0.851500,0.062855,-0.542502,-1.223717,-0.977140,-0.714617,-1.107236,-0.557628,0.482972,0.404580,0.293036,0.607996,1.456899,-0.351650,-0.914102,-0.293972,-0.796857
389,-0.163397,-0.862801,-0.968631,1.665207,-0.608129,-0.292214,-0.064955,-0.234352,-0.411318,-0.638865,-0.915441,-0.161134,2.394811,0.111309,1.721244,0.420884,-1.205619,-0.628927,2.050190

In [13]:
y = np.where(y=='Yes',1,0)

In [14]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
#Create Train-test dataset split from manual split 

trainX, testX, trainY, testY = skm.train_test_split(x, y, test_size=0.25, random_state=53)
print("shape of train split: ",trainX.shape,trainY.shape)
print("shape of test split: ",testX.shape,testY.shape)

shape of train split:  (292, 19) (292,)
shape of test split:  (98, 19) (98,)

In [16]:
# NB on Manual Split
clf = GaussianNB()
clf.fit(trainX,trainY)
prediction = clf.predict(testX)
print("Accruracy of NB(%): \n",accuracy_score(testY, prediction)*100)
fpr, tpr, _ =roc_curve(testY,prediction)
print("AUC of NB (%): \n", auc(fpr,tpr)*100)

Accruracy of NB(%):
 95.91836734693877
AUC of NB (%):
 95.10244877561217

In [18]:
#create arrays for storing 
accarray = []
aucarray = []

#Define the split into 4 folds 

kf = skm.StratifiedKFold(n_splits=5, random_state=99, shuffle =False)
print(list(kf.split(x,y)))

[(array([ 74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
        87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
       100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203,
       204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216,
       217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229,
       230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
       243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
       256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268,
       269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281,
       282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 318, 319,
       320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332,
       333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345,
       346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358,
       359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371,
       372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384,
       385, 386, 387, 388, 389]), array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73, 293, 294, 295, 296,
       297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309,
       310, 311, 312, 313, 314, 315, 316, 317])), (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73, 147, 148, 149, 150,
       151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
       164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
       177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
       190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
       203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
       216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
       242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
       255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
       268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280,
       281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293,
       294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306,
       307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 342, 343,
       344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356,
       357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369,
       370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382,
       383, 384, 385, 386, 387, 388, 389]), array([ 74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
        87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
       100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 318, 319, 320, 321, 322,
       323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335,
       336, 337, 338, 339, 340, 341])), (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
       242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
       255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
       268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280,
       281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293,
       294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306,
       307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319,
       320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332,
       333, 334, 335, 336, 337, 338, 339, 340, 341, 366, 367, 368, 369,
       370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382,
       383, 384, 385, 386, 387, 388, 389]), array([147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
       160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
       173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185,
       186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198,
       199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211,
       212, 213, 214, 215, 216, 217, 218, 219, 342, 343, 344, 345, 346,
       347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359,
       360, 361, 362, 363, 364, 365])), (array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 293,
       294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306,
       307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319,
       320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332,
       333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345,
       346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358,
       359, 360, 361, 362, 363, 364, 365]), array([220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232,
       233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245,
       246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258,
       259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271,
       272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284,
       285, 286, 287, 288, 289, 290, 291, 292, 366, 367, 368, 369, 370,
       371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383,
       384, 385, 386, 387, 388, 389]))]

<b> 
In above result there are 4 tuples and in every tuple there are to arrays which represents the train test splits.
kf.split() function shows give the row indexes of splitted data.</b>

In [34]:
for train_index, test_index in kf.split(x,y):
    trainX,testX = x[train_index], x[test_index]
    trainY, testY = y[train_index],y[test_index]
    
    clf = KNeighborsClassifier(n_neighbors = 5)
    clf.fit(trainX,trainY)
    prediction = clf.predict(testX)
    accarray= np.append(accarray,accuracy_score(testY,prediction)*100)
print("Average accuracy of K-Nearest Neighbor(%):", np.mean(accarray))

Average accuracy of K-Nearest Neighbor(%): 92.75518067270644

In [35]:
accarray2 = []
aucarray2 = []
for train_index, test_index in kf.split(x,y):
    trainX,testX = x[train_index], x[test_index]
    trainY, testY = y[train_index],y[test_index]
    
    clf2 = KNeighborsClassifier(n_neighbors = 3)# trying with K = 3 
    clf2.fit(trainX,trainY)
    prediction2 = clf.predict(testX)
    accarray2= np.append(accarray2,accuracy_score(testY,prediction2)*100)
print("Average accuracy of K-Nearest Neighbor(%):", np.mean(accarray2))

Average accuracy of K-Nearest Neighbor(%): 94.87660106216808

In [38]:
accarray3 = []
aucarray3 = []
for train_index, test_index in kf.split(x,y):
    trainX,testX = x[train_index], x[test_index]
    trainY, testY = y[train_index],y[test_index]
    
    clf3 = KNeighborsClassifier(n_neighbors = 6)# trying with K = 3 
    clf3.fit(trainX,trainY)
    prediction3 = clf.predict(testX)
    accarray3= np.append(accarray3,accuracy_score(testY,prediction3)*100)
print("Average accuracy of K-Nearest Neighbor(%):", np.mean(accarray3))
precision_score(testY,)

Average accuracy of K-Nearest Neighbor(%): 94.87660106216808

In [5]:
help(precision_score())

SyntaxError: invalid syntax (<ipython-input-5-7ac79292e8f2>, line 1)